AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a randomly named S3 bucket and outputs its name'

Resources:
  RandomS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - 'random-bucket'
          - !Select
            - 2
            - !Split
              - '-'
              - !Select
                - 2
                - !Split
                  - '/'
                  - !Ref 'AWS::StackId'

  CloudHealthReadOnlyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CloudHealth-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::454464851268:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': 16160bc0fbdbbca17d39cbeb5bd83f
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::454464851268:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': 16160bc0fbdbbca17d39cbeb5bd83f

Outputs:
  RandomS3BucketName:
    Value: !Ref RandomS3Bucket
    Description: 'The name of the randomly created S3 bucket'
